version: "3"
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: postgres
      POSTGRES_DB: portfolio

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080