version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PD_API

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/conf.d:/etc/nginx/conf.d
      - ./frontend/pdisplay:/var/www/html/pdisplay

  datastore:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: postgres
      POSTGRES_DB: portfolio

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

