version: "3"
services:
  web_app:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_USER: postgres
      DB_NAME: portfolio
      DB_PASSWORD: postgres
      DB_HOST: db
    depends_on:
      - db
      - adminer

  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: postgres
      POSTGRES_DB: portfolio

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080